In [7]:
import tensorflow as tf
import os
import cv2
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
import seaborn as sns

In [8]:
train = pd.read_csv("./data/train.csv")
test = pd.read_csv("./data/test.csv")

In [10]:
train

,product_type,air_temp [K],process_temp [K],torque [Nm],tool_wear [min],target
0,0.0,-1.588786,-1.334958,0.509232,-1.090530,0
1,1.0,-1.485697,-1.108159,0.692203,0.307820,0
2,0.0,-1.207357,-1.478597,1.317821,-1.518596,1
3,0.0,0.452378,0.675995,0.240406,1.221028,1
4,0.0,-1.073341,-0.654560,-0.131164,0.578929,0
...,...,...,...,...,...,...
11611,0.0,0.864735,0.751594,0.849135,1.178222,1
11612,0.0,0.472996,0.328236,-0.074866,1.206760,0
11613,0.0,0.163729,1.386632,-0.539329,0.550391,0
11614,0.0,0.730719,0.456755,1.384676,-1.033455,1
11615,0.0,0.668866,0.381156,0.934287,0.892844,1

In [11]:
test

,product_type,air_temp [K],process_temp [K],torque [Nm],tool_wear [min],target
0,0.0,-0.970252,-0.276562,0.051806,0.265013,0
1,0.0,-0.599131,-0.669680,-0.219835,1.178222,1
2,2.0,1.658521,2.067030,0.340336,-1.761167,0
3,1.0,0.936897,-0.049763,-0.504143,-1.347370,0
4,0.0,1.658521,1.613431,0.086993,-0.391355,0
...,...,...,...,...,...,...
2900,0.0,-0.325945,0.063637,1.305858,-0.519775,1
2901,2.0,-0.609440,-1.032559,0.030694,0.935651,0
2902,0.0,-0.836236,-0.397521,-1.215616,0.479047,1
2903,0.0,-0.037295,0.184596,-2.435185,0.093787,1
2904,2.0,1.091531,0.214836,0.693610,-1.532865,1

In [9]:
from tensorflow import keras

model = keras.Sequential([
    keras.layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')  # binario: normal/failure
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(X_train, y_train,
                    epochs=50,
                    batch_size=32,
                    validation_split=0.2)

NameError: name 'X_train' is not defined